map_size: 50 #[width, height] size of the map
start_position: [0, 0] # The x and y location of the start point
goal_position: [49, 30] #The x and y location of the goal point
max_thread: 5 #The maximum thread of GPU can be used for the planning. AKA the maximum number of nodes can be explored each time
